# Generated by Django 5.2.17 on 2026-08-13 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('certificate_title', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(upload_to='certificates/docs/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qrcodes/')),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='VALID', max_length=15)),
                ('issued_by', models.CharField(default='Educational Institution', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
